I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/open_map.rpy", line 4, in script
    return
Exception: Could not find return label (u'game/script.rpy', 1609081231, 11, 'end_translate').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/open_map.rpy", line 4, in script
    return
  File "C:\Users\yoina\Documents\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 1507, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\yoina\Documents\Renpy\renpy-7.3.5-sdk\renpy\execution.py", line 696, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/script.rpy', 1609081231, 11, 'end_translate').

Windows-8-6.2.9200
Ren'Py 7.3.5.606
AddictionVN 1.0
Mon Dec 28 17:50:03 2020
